# version: "3"
# services:
#   app:
#     container_name: containerize_app_1
#     image: "nginx:alpine"  # Replace with your application's Docker image
#     ports:
#       - "3000:3000"  # Map the application port (change as needed)
#     environment:
#       - NODE_ENV=production  # Example environment variable, customize as needed
#     volumes:
#       - ./app:/usr/src/app  # Bind mount your app directory

#   nginx:
#     container_name: containerize_nginx_1
#     build:
#       context: .
#       dockerfile: Dockerfile.nginx
#     ports:
#       - "80:80"
#       - "443:443"
#     volumes:
#       - ./nginx.conf:/etc/nginx/nginx.conf  # Bind mount your Nginx config file
#       - ./nginx/files:/etc/nginx/ssl  # Bind mount your SSL certificates
#     depends_on:
#       - app


#######################################################################################################


version: '3.8'

services:
  app:
    build:
      context: ./app
    volumes:
      - ./app/src:/app
    environment:
      - FLASK_ENV=development
    expose:
      - "8000"

  nginx:
    build:
      context: ./nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app










